
const CREATE_ACTIVITY = 'CREATE-ACTIVITY'
const GET_ALL_ACTIVITIES = 'GET-ALL-ACTIVITIES'
const SET_FILTER_BY_ACTIVITY = 'SET-FILTER-BY-ACTIVITY'

export { 
    CREATE_ACTIVITY, 
    GET_ALL_ACTIVITIES,
    SET_FILTER_BY_ACTIVITY
}