const SET_CURRENT_PAGE = 'SET-CURRENT-PAGE'
const SET_NAME_COUNTRIES = 'SET-NAME-COUNTRIES'
const SET_ORDER = 'SET-ORDER'
const SET_FILTER_BY_CONTINENTS = 'SET-FILTER-BY-CONTINENTS'
const SET_NEW_ACTIVITY = 'SET-NEW-ACTIVITY'
const CLEAR_NEW_ACTIVITY = 'CLEAR-NEW-ACTIVITY'
const SET_ERROR = 'SET-ERROR'

export {
    SET_CURRENT_PAGE,
    SET_NAME_COUNTRIES,
    SET_ORDER,
    SET_FILTER_BY_CONTINENTS,
    SET_NEW_ACTIVITY,
    CLEAR_NEW_ACTIVITY,
    SET_ERROR
}