const GET_ALL_COUNTRIES = 'GET-ALL-COUNTRIES'
const GET_COUNTRY_BY_ID = 'GET-COUNTRY-BY-ID'
const GET_COUNTRIES_BY_NAME = 'GET-COUNTRIES-BY-NAME'
const SET_CURRENT_COUNTRIES = 'SET-CURRENT-COUNTRIES'

export { 
    GET_ALL_COUNTRIES, 
    GET_COUNTRY_BY_ID, 
    GET_COUNTRIES_BY_NAME,
    SET_CURRENT_COUNTRIES
}