const GET_ALL_COUNTRIES = 'GET-ALL-COUNTRIES'
const GET_COUNTRIES_BY_NAME = 'GET-COUNTRIES-BY-NAME'
const SET_CURRENT_COUNTRIES = 'SET-CURRENT-COUNTRIES'
const SET_COUNTRIES_BY_ACITVITIES = 'SET-COUNTRIES-BY-ACITVITIES'

export { 
    GET_ALL_COUNTRIES, 
    GET_COUNTRIES_BY_NAME,
    SET_CURRENT_COUNTRIES,
    SET_COUNTRIES_BY_ACITVITIES
}